services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: vip-main-web
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./instance:/app/instance
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_ENV=production
      - TELEGRAM_BOT_TOKEN=7528348229:AAG147qHcmTEHVujdpSabSXSmO_JgT6Tnd0
      - TELEGRAM_CHAT_ID=1080893983
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=vasel4uk
    restart: unless-stopped

  telegram-bot:
    build: 
      context: .
      dockerfile: Dockerfile
    image: vip-main-telegram
    command: python telegram_bot.py
    volumes:
      - .:/app
      - ./instance:/app/instance
    environment:
      - TELEGRAM_BOT_TOKEN=7528348229:AAG147qHcmTEHVujdpSabSXSmO_JgT6Tnd0
      - TELEGRAM_CHAT_ID=1080893983
    restart: unless-stopped